version: '3.7'

services:
  isomorhic:
    container_name: isomorphic
    restart: unless-stopped
    build:
      context: .
    tty: true
    ports:
    - 80:3000
    volumes:
      - ./:/app
      - /app/node_modules
